version: '3.8'

services:
  nginx:
    image: ${DOCKER_HUB_URL}/${NAME}-nginx:${ENV}
    container_name: ${NAME}-${ENV}-nginx
    command: [ "./entrypoint.sh" ]
    expose:
      - "443"
    restart: always
    env_file:
      - .env
    networks:
      - net

networks:
  net:
    name: ${NAME}-${ENV}-net