version: '3.8'

services:
  # Worker
  worker:
    image: ${DOCKER_HUB_URL}/${NAME}-worker:${ENV}
    container_name: ${NAME}-${ENV}-worker
    command: [ "scripts/entrypoint.worker.sh" ]
    restart: always
    depends_on:
      - redis
      - rabbitmq
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    networks:
       - net

  # Redis
  redis:
    image: redis:7.4.0-alpine3.20
    container_name: ${NAME}-${ENV}-redis
    command: redis-server --requirepass ${REDIS_PASS}
    restart: always
    expose:
      - 6379
    env_file:
      - .env
    volumes:
      - volume-redis:/data
    networks:
      - net

  # Rabbitmq
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: ${NAME}-${ENV}-rabbitmq
    restart: always
    expose:
      - 5672
      - 15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    env_file:
      - .env
    volumes:
      - volume-rabbitmq:/var
    networks:
      - net

volumes:
  volume-redis:
    name: ${NAME}-${ENV}-redis-data
  volume-rabbitmq:
    name: ${NAME}-${ENV}-rabbitmq-data

networks:
  net:
    name: ${NAME}-${ENV}-net