version: '3.8'

services:
  # App
  app:
    image: ${DOCKER_HUB_URL}/${NAME}-app:${ENV}
    container_name: ${NAME}-${ENV}-app
    command: [ "scripts/entrypoint.sh" ]
    ports:
      - "8888:${BASE_PORT}"
    restart: unless-stopped
    depends_on:
      - alembic
    volumes:
      - volume-app-log:/app/logs
      - volume-app-worker-shared:/app/${STATIC_URL}/${WORKER_DIRECTORY}
    env_file:
      - .env
    networks:
      - net

  # Migration
  alembic:
    image: ${DOCKER_HUB_URL}/${NAME}-app:${ENV}
    container_name: ${NAME}-${ENV}-alembic
    command: [ "alembic", "-c", "alembic/alembic.ini", "upgrade", "head" ]
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - net

  # Database
  db:
     image: postgres:13.2
     container_name: ${NAME}-${ENV}-db
     restart: unless-stopped
     expose:
       - 5432
     environment:
       - POSTGRES_USER=${POSTGRES_USER}
       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
       - POSTGRES_DB=${POSTGRES_DB}
     volumes:
       - volume-db:/var/lib/postgresql/data
     env_file:
       - .env
     networks:
       - net

volumes:
  volume-app-log:
    name: ${NAME}-${ENV}-app-log-data
  volume-app-worker-shared:
    name: ${NAME}-${ENV}-app-worker-shared-data
  volume-db:
    name: ${NAME}-${ENV}-db-data

networks:
  net:
    name: ${NAME}-${ENV}-net